export enum AppActionsType {
  CHANGE_LANG_TYPE = 'CHANGE_LANG_TYPE',
  TEMP_USER_REGISTRATION = 'TEMP_USER_REGISTRATION',
}

export enum UserActionsType {
  SET_TOKEN = 'SET_TOKEN',
  USER_DETAILS = 'USER_DETAILS',
  SET_USER_EXPENSES = 'SET_USER_EXPENSES',
}
